### ISSUE TITLE
No option to save LSTM model

### ISSUE THREAD

**Issue by KnightLock** [mikekeith52/scalecast#12]
I trained an LSTM model and couldn't figure out a way to save my model in any format. I've been through all of the docs provided but there's no way to get the job done. Need help.

**Comment by mikekeith52** [comment]
This has not been added until now because having this model in the object's attributes causes some other methods to break--anything that attempts to create an object deepcopy. I think there is a pretty simple work-around though. I will add an attribute called `tf_model` that will be the trained tensorflow model but will not be saved to the object's memory and will be deleted before deepcopy() is called. We can plan to implement this in 0.14.3 on Friday 9/23/22.

**Comment by KnightLock** [comment]
> This has not been added until now because having this model in the object's attributes causes some other methods to break--anything that attempts to create an object deepcopy. I think there is a pretty simple work-around though. I will add an attribute called `tf_model` that will be the trained tensorflow model but will not be saved to the object's memory and will be deleted before deepcopy() is called. We can plan to implement this in 0.14.3 on Friday 9/23/22.

Thank you so very much ! ❤

**Comment by mikekeith52** [comment]
This is implemented and the version number is 0.14.4. After specifying the LSTM forecast, the model should be available by calling `Forecaster.tf_model`. You can save this the same way you would any other model from TensorFlow. It will go away if you change the estimator. Let me know if you experience any issues with it.
