### ISSUE TITLE
use_boxcox parameter in holt winters

### ISSUE THREAD

**Issue by callmegar** [mikekeith52/scalecast#19]
with this grid:

hwes = {
    'trend':['add','mul'],
    'seasonal':['add','mul'],
    'damped_trend':[True,False],
    'initialization_method':[None,'estimated','heuristic'],
    'use_boxcox':[True,False],
    'seasonal_periods':[168],
}

I get this result which I do not understand as it is True or False: 

`File ~/.local/share/virtualenvs/scalecast-0HQw5DtN/lib/python3.10/site-packages/statsmodels/tsa/holtwinters/model.py:337, in ExponentialSmoothing._boxcox(self)
    335     y = boxcox(self._y, self._use_boxcox)
    336 else:
--> 337     raise TypeError("use_boxcox must be True, False or a float.")
    338 return y

TypeError: use_boxcox must be True, False or a float.`

I think the issue may be here:
`File ~/.local/share/virtualenvs/scalecast-0HQw5DtN/lib/python3.10/site-packages/statsmodels/tsa/holtwinters/model.py:291, in ExponentialSmoothing.__init__(self, endog, trend, damped_trend, seasonal, seasonal_periods, initialization_method, initial_level, initial_trend, initial_seasonal, use_boxcox, bounds, dates, freq, missing)
    289 self._use_boxcox = use_boxcox
    290 self._lambda = np.nan
--> 291 self._y = self._boxcox()
    292 self._initialize()
    293 self._fixed_parameters = {}`

**Comment by mikekeith52** [comment]
This isn't the first time I've seen this issue but I really started digging into it after seeing this issue. Turns out, the type True gets converted from a `bool` to a `numpy.bool_` type between the time the model is tuned and tested. This causes the check `kwargs['use_boxcox'] is True` to return `False`, thus raising the issue which originates from statsmodels. Incredbile. I will implement a fix in 0.15.3.

**Comment by mikekeith52** [comment]
Please try it out and let me know.
