### ISSUE TITLE
How to save model if I also used scalecast to find optimal transformation?

### ISSUE THREAD

**Issue by fstayco** [mikekeith52/scalecast#57]
Good day.  I used scalecast to build an auto-time series pipeline, which includes finding the optimal transformation and uses models [       'mlr', 'lasso', 'ridge', 'elasticnet', 'xgboost', 'lightgbm', 'knn'].  How do I save the optimal transformation found and the best model derived, for use in production.  

Apologies in advance as I am new to using scalecast.  I'll appreciate your assistance on this.

**Comment by mikekeith52** [comment]
You would save out your Pipeline, SeriesTransformer, and/or Forecaster objects in a pickle, which would include all fitted models and the entire series. Every time you made a prediction, you would need to refit your models. It's a solution that works for smaller-to-intermediate series or series that don't need a prediction very often, but it's not ideal for every situation. If that sounds like something you would pursue, let me know and we can work on it. Otherwise, I don't think I have any ideas that would work within scalecast.

**Comment by fstayco** [comment]
Thanks heaps for the speedy reply.  Is there a way to use the originally fit best transformer and model to new data (either purely within scalecast or in combination with other libraries)?

**Comment by mikekeith52** [comment]
Yes there is a way to do that within scalecast. Here is an example:

```python
from scalecast.Forecaster import Forecaster
from scalecast.util import find_optimal_transformation

f1 = Forecaster(...)
f2 = Forecaster(...)

f1.add_ar_terms(12)
f2.add_ar_terms(12)

# find optimal transformation on series 1
transformer, reverter = find_optimal_transformation(f1)
f1 = transformer.fit_transform(f1)

# tune lasso model on series 1
f1.set_estimator('lasso')
f1.tune()
chosen_params = f1.best_params # save best params -- these will also be in f1.history['lasso']['HyperParams']
f1.auto_forecast()

# apply transformation to series 2
f2 = transformer.fit_transform(f2)

# apply lasso model with optimal hyperparams to series 2
f2.set_estimator('lasso')
f2.manual_forecast(**chosen_params)
```

**Comment by mikekeith52** [comment]
Are we okay to close this issue?

**Comment by fstayco** [comment]
Yes, @mikekeith52 .  You have been quite helpful.

**Comment by mikekeith52** [comment]
Glad I could help! Thanks for using the package and raising the issue!
