### ISSUE TITLE
Generating future values does not show in plot

### ISSUE THREAD

**Issue by MartinMashalov** [mikekeith52/scalecast#8]
Hello, 

I am using scalecast for a timeseries project consisting of predicting future asset prices. I am currently deploying my model in production but I cannot generate any future values beyond my testing dataset. At the beginning of my script, I have written "f.generate_future_dates(20)" but the f.plot() method does not return the predictions for the next 20 units. 

Would you please guide me for how to generate and plot these next 20 units? 

Thank you. 

Martin

**Comment by mikekeith52** [comment]
Hi,

I'm not sure how that error could have happened. As long as the object is initialized with the default `Forecaster(require_future_dates=True)` configuration, it should forecast through a future horizon whenever a model is called. Would you be able to share the part of the script that runs the forecasting process with scalecast, from the time you initialized the object until when the forecasts are called?

**Comment by MartinMashalov** [comment]
Hi Michael, 

Thank you for your response. The parts of the script are: 

To forecast: `f.manual_forecast(call_me="gbt_default_dynamic", dynamic_testing=False)`
To plot: `f.plot_test_set(
    models=["gbt_default_dynamic"], include_train=False
)`

Also, could you briefly explain the dynamic vs. non-dynamic functionality?

**Comment by mikekeith52** [comment]
If you try:

```python
f.plot(models='gbt_default_dynamic')
```

What happens? Do you see the forecast into future periods?

"Dynamic" in scalecast means recursively replacing autoregressive values with predictions of those values when testing models out-of-sample in periods where those values would be unknown in a true out-of-sample forecast. So `dynamic_testing=False` is akin to taking a series of one-step forecasts over the test-set horizon because it lets the model know the true values of each autoregressive term across the entire test-set timeframe. It is slightly more efficient so it can be useful when you have limited computing resources. But in scalecast, the default is `dynamic_testing=True` to give a true sense of how the forecast actually performs out of sample.

**Comment by MartinMashalov** [comment]
Ok I got it to work with the `f.plot() `method. Thank you for explaining the dynamic functionality, makes sense now. I will close the issue. I appreciate your work.
